homepage: "https://github.com/deanmalmgren/textract"
language: python
primary_contact: ""
main_repo: "https://github.com/deanmalmgren/textract"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
