homepage: "https://github.com/wention/BeautifulSoup4"
language: python
primary_contact: ""
main_repo: "https://github.com/wention/BeautifulSoup4"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
